version: "1.1.0"

name: fastapi

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: myhelloworldcontainer
    ports:
      - "8000:8000"  # Expose container port 8000 to host port 8000  
    networks:
      - my-api-net
  postgres_db:
    image: postgres:latest
    restart: always
    container_name: postgresCount
    environment:
      - POSTGRES_USER = ziakhan
      - POSTGRES_PASSWORD = my_password
      - POSTGRES_DB = mydatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - my-api-net


volumes:
  postgres_db:
    driver: local


networks:
  my-api-net:


